### ISSUE TITLE
Meta-Issue: Example case for instance data description in triples

### ISSUE THREAD

**Issue by k-knosala** [OpenEnergyPlatform/oeo-extended#5]
## Description of the issue

Although I did not not participate in the developer meeting (but will do in the next one) I understood from discussions with @p-kuckertz that a central goal of the ontology development is to use it to describe real world data for modeling purposes. 

OWL can give an umambiguous definition to instance data. This makes different data sources comparable and mergable. Futher, it allows to validate the instance data for ontological consistency and constraints to identify missing, false or inconsistent data using a Shapes Constraint Language ([SHACL](https://spinrdf.org/shacl-and-owl.html)).

To describe instance data we require a trible of class, attribute and constraint.

In this issue I would like to present a short example of instance data for an electrolyzer to discuss the development of such triples in the ontology. Please note, that this is just an example to identify the requirements for decribing instance data in the OEO and as a basis for further discussions.

EXAMPLE:

* A electrolysis system has none or many
    * electrolysis stack
    * gas compression
    * gas cooling
    * gas purification
    * water conditioning
    * water cooling
    * water pump
    * power electronics

* A electrolysis system has none or one 
    * container

_General properties:_

| attribute      | quantity value | example unit | example range | example data |
|----------------|----------------|--------------|---------------|--------------|
| manufacturer   | -              | -            | -             | AREVA H2GEN  |
| series         | -              | -            | -             | E10          |
| reference year | year           | -            | -             | 2020         |
|                |                |              |               |              |

	
_Economic properties:_

| attribute       | quantity value     | example unit | example range | example data |
|-----------------|--------------------|--------------|---------------|--------------|
| Investfix       | currency           | EUR          | >0            | -            |
| Invest variable | currency per power | EUR/kW       | >0            | -            |
| OPEX fix        | currency           | EUR          | >0            | -            |
| OPEX variable   | currency per power | EUR/kW       | >0            | -            |
|                 |                    |              |               |              |

_Technical Properties:_

| attribute                     | quantity value          | example unit | example range | example data                 |
|-------------------------------|-------------------------|--------------|---------------|------------------------------|
| input                         | List[commodity]         | -            | -             | DC power, water              |
| output                        | List[commodity]         | -            | -             | hydrogen, oxygen, waste-heat |
| electrical power              | power                   | kW           | >0            | 80                           |
| specific energy consumption   | energy per volume       | kWh/Nm^3     | >0            | 5.3                          |
| voltage level                 | voltage                 | V            | >0            | 400                          |
| frequency                     | frequency               | Hz           | >0            | 50                           |
| part load min                 | ratio                   | %            | [0,100]       | -                            |
| part load max                 | ratio                   | %            | [0,100]       | -                            |
| input water mass flow max     | volume per time         | l/h          | >0            | 20                           |
| input water conductivity max  | conductivity per length | μS/cm        | >0            | 2000                         |
| input water PH value min      | PH value                | -            | [0,14]        | 4                            |
| input water PH value max      | PH value                | -            | [0,14]        | 10                           |
| input water temperature min   | temperature             | °C           | >0            | 5                            |
| input water temperature max   | temperature             | °C           | >0            | 40                           |
| input water pressure min      | pressure                | barg         | >0            | 2                            |
| input water pressure max      | pressure                | barg         | >0            | 6                            |
| output hydrogen mass flow nom | volume per time         | Nm^3/h       | >0            | 10                           |
| output hydrogen pressure max  | pressure                | barg         | >0            | 50                           |
| output hydrogen purity min    | -                       | -            | >0            | 3.0                          |
| output hydrogen purity max    | -                       | -            | >0            | -                            |
| output oxygen mass flow nom   | volume per time         | Nm^3/h       | >0            | 5                            |
| output oxygen pressure nom    | pressure                | barg         | >0            | 13                           |
| output oxygen purtiy min      | -                       | -            | >0            | -                            |
| output waste-heat mass flow   | volume per time         | m^3/h        | >0            | 2                            |
| output waste-heat energy flow | power                   | kWh/h        | >0            | -                            |
| output waste-heat temperature | temperature             | K            | >0            | -                            |
| lifetime                      | time                    | a            | >0            | 20                           |
| ambient temperaturem min      | temperature             | °C           | >0            | 3                            |
| ambient temperature max       | temperature             | °C           | >0            | 40                           |
| ambient humidity min          | humidity                | %            | [0,100]       | 0                            |
| ambient humidity max          | humidity                | %            | [0,100]       | 95                           |
|                               |                         |              |               |                              |

## Workflow checklist

- [x] I discussed the issue with someone else than me before working on a solution
- [x] I already read the **latest** version of the [workflow](https://github.com/OpenEnergyPlatform/ontology/blob/dev/CONTRIBUTING.md) for this repository
- [x] The [goal](https://github.com/OpenEnergyPlatform/ontology/blob/dev/README.md) of this ontology is clear to me 

I am aware that
- [x] every entry in the ontology should have a definition
- [x] classes should arise from concepts rather than from words
